" Load plugins
let g:plugins_file_path = '~/.vim/plugins.vim'
if filereadable(expand(g:plugins_file_path))
  exe ':source ' . g:plugins_file_path
endif

" Color scheme
try
  colorscheme gruvbox
  set background=dark
catch
endtry

set nocompatible " We don't need to be vi compatible
set autoread " Set to auto read when a file is changed from the outside
set mouse=nvi " Enable mouse
set ruler " Show current position
set cursorline " Highlight current line
set hid " Hide buffer when it is abandoned
set hidden " Allow buffers in background
set number " Show line numbers
set numberwidth=4 " Gutter width

set backspace=eol,start,indent " Sane backspace
set whichwrap+=<,>,h,l

set lazyredraw " Don't redraw while executing a macro (for performance)
set magic " Turn on magic for regular expressions
set mat=2 " How many tenths of a second to blink when matching brackets
set showmatch " Show matching brackets with text indicator over them 

" Show white space characters
set list
set listchars=tab:▸\ ,eol:¬

" Make search tolerable as described in
" http://stevelosh.com/blog/2010/09/coming-home-to-vim/
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch

set expandtab " Use spaces instead of tabs 
set shiftwidth=2
set tabstop=8
set softtabstop=2

set autoindent " Auto indent
set smartindent " Smart indent
set wrap " Wrap lines
set cindent

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Turn backup off
set nobackup
set nowb
set noswapfile

" Let's save undo info!
if !isdirectory($HOME."/.vim/undo-dir")
    call mkdir($HOME."/.vim/undo-dir", "", 0700)
endif
set undodir=~/.vim/undo-dir
set undofile

set wildmenu " Turn on the WiLd menu
set wildmode=longest:full,full
set wildignorecase " Ignore case

set wildignore=*.o,*~,*.pyc " Ignore compiled files
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store " Ignore subversion and macOS files.

set clipboard=unnamed " Copy to clipboard

autocmd BufRead,BufNewFile *.py setlocal shiftwidth=2 tabstop=2 softtabstop=2 " Indentation for Python
autocmd BufRead,BufNewFile *.js setlocal shiftwidth=2 tabstop=2 softtabstop=2" Indentation for JavaScript

au FocusLost * :wa " Save when focus is lost

au BufReadPost Jenkinsfile set syntax=groovy " Groovy syntax for Jenkinsfile
au BufReadPost Fastfile set syntax=ruby " Groovy syntax for Fastfile

" Load plugins
let g:keymap_file_path = '~/.vim/keymap.vim'
if filereadable(expand(g:keymap_file_path))
  exe ':source ' . g:keymap_file_path
endif


