" Load plugins
let g:plugins_file_path = '~/.vim/plugins.vim'
if filereadable(expand(g:plugins_file_path))
  exe ':source ' . g:plugins_file_path
endif

" Color scheme
try
  colorscheme gruvbox
  set background=dark
catch
endtry

set autoread " Set to auto read when a file is changed from the outside
set mouse=nvi " Enable mouse
set ruler " Show current position
set cursorline " Highlight current line
set hid " Hide buffer when it is abandoned
set hidden " Allow buffers in background

set backspace=eol,start,indent " Sane backspace
set whichwrap+=<,>,h,l

set ignorecase " Ignore case when searching
set smartcase " Be smart about casing
set incsearch " Make search act like in modern browsers
set lazyredraw " Don't redraw while executing a macro (for performance)
set magic " Turn on magic for regular expressions
set mat=2 " How many tenths of a second to blink when matching brackets
set showmatch " Show matching brackets with text indicator over them 

set expandtab " Use spaces instead of tabs 
set shiftwidth=2
set tabstop=8
set softtabstop=2

set ai " Auto indent
set si " Smart indent
set wrap " Wrap lines

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Turn backup off
set nobackup
set nowb
set noswapfile

set wildmenu " Turn on the WiLd menu
set wildmode=full
set wildignorecase " Ignore case

set wildignore=*.o,*~,*.pyc " Ignore compiled files
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store " Ignore subversion and macOS files.

set clipboard=unnamed " Copy to clipboard

autocmd FileType python setlocal shiftwidth=2 tabstop=2 " Indentation for Python

" Load plugins
let g:keymap_file_path = '~/.vim/keymap.vim'
if filereadable(expand(g:keymap_file_path))
  exe ':source ' . g:keymap_file_path
endif


